name: Development

on:
  push:
    branches-ignore: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:

      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          key:  development-node-modules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          path: '**/node_modules'

      - name: Install dependencies
        run:  yarn --frozen-lockfile

      - name: Build
        run:  yarn build
